# Generated by Django 6.0.6 on 2026-06-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to-do', 'To Do'), ('in-progress', 'In Progress'), ('in-review', 'In Review'), ('done', 'Done')], default='to-do', max_length=20),
        ),
    ]
