# Generated by Django 6.0.6 on 2026-06-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0002_alter_task_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
